### ISSUE TITLE
Hi ,you can add these figures in your readme or anywhere you find appropriate

### ISSUE THREAD

**Issue by p0p4k** [JunityZhan/Understanding-VITS#2]
![image](https://github.com/JunityZhan/Understanding-VITS/assets/8834712/20dbab6a-67ee-4cd7-adc1-d12166e6d617)
![image](https://github.com/JunityZhan/Understanding-VITS/assets/8834712/5d93bc5a-63f7-46bc-9f59-a364372c5b50)

**Comment by p0p4k** [comment]
also this https://github.com/coqui-ai/TTS/discussions/2025

**Comment by JunityZhan** [comment]
Thank you very much, I added them in the end of models.ipynb. MAS is indeed the most interesting part in this model.
